# Netlify Configuration for OxCal

[build]
  command = "pnpm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# PWA Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/manifest+json"

# Terms data JSON
[[headers]]
  for = "/terms.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/json"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}

# Environment-specific context
[context.production]
  command = "pnpm run build"
  
[context.deploy-preview]
  command = "pnpm run build"
  
[context.branch-deploy]
  command = "pnpm run build"

# Dev environment
[dev]
  command = "pnpm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true